const projects={
booking:{name:['预约与客户管理','Booking & Client Manager'],tag:['让服务业务全天候接受预约','Let service businesses take bookings 24/7'],stats:[['今日预约','Today','8'],['本周收入','Weekly revenue','$3,240'],['到场率','Show rate','92%']],form:[['客户姓名','Client name','text'],['服务项目','Service','select'],['预约时间','Appointment time','datetime-local']],items:[['09:30 · 产品咨询','09:30 · Product consultation'],['11:00 · 复诊预约','11:00 · Follow-up appointment'],['15:30 · 私教课程','15:30 · Coaching session']]},
support:{name:['AI 客服知识库','AI Support Knowledge Base'],tag:['基于可信来源回答客户问题','Answers customer questions from trusted sources'],stats:[['已索引文档','Indexed docs','128'],['解决率','Resolution rate','81%'],['平均响应','Avg response','1.8s']],form:[['客户问题','Customer question','textarea'],['知识范围','Knowledge scope','select']],items:[['退款政策 · 来源 #12','Refund policy · Source #12'],['API 限制 · 来源 #31','API limits · Source #31'],['团队权限 · 来源 #44','Team permissions · Source #44']]},
commerce:{name:['电商运营自动化','Commerce Operations Hub'],tag:['把订单数据转化为可执行决策','Turns order data into actions'],stats:[['今日订单','Orders today','146'],['低库存','Low stock','7'],['自动任务','Automations','23']],form:[['商品/SKU','Product / SKU','text'],['库存数量','Stock count','number'],['规则','Automation rule','select']],items:[['SKU-104 · 预计 2 天售罄','SKU-104 · 2 days to stockout'],['SKU-208 · 补货单已生成','SKU-208 · Reorder created'],['周报 · 已发送','Weekly report · Sent']]},
monitor:{name:['网站健康监控','Website Health Monitor'],tag:['在客户发现故障前定位问题','Finds failures before customers do'],stats:[['在线率','Uptime','99.97%'],['监控站点','Monitors','12'],['平均响应','Avg latency','184ms']],form:[['网站地址','Website URL','url'],['检查频率','Check interval','select']],items:[['api.example.com · 正常','api.example.com · Healthy'],['shop.example.com · 变慢','shop.example.com · Degraded'],['docs.example.com · 正常','docs.example.com · Healthy']]},
invoice:{name:['发票与费用识别','Invoice & Expense Intelligence'],tag:['从收据到结构化账目只需几秒','From receipt to structured ledger in seconds'],stats:[['本月处理','Processed','284'],['识别准确率','Accuracy','97.4%'],['待审核','Needs review','6']],form:[['商家名称','Merchant','text'],['金额','Amount','number'],['费用分类','Category','select']],items:[['Cloud Hosting · $82.00','Cloud Hosting · $82.00'],['Office Supply · $46.20','Office Supply · $46.20'],['Travel · $218.40','Travel · $218.40']]},
delivery:{name:['客户项目交付门户','Client Delivery Portal'],tag:['让里程碑、文件与验收保持同步','Keeps milestones, files and approvals aligned'],stats:[['进行中项目','Active projects','6'],['准时交付','On-time','96%'],['待验收','Awaiting approval','3']],form:[['里程碑名称','Milestone name','text'],['截止日期','Due date','date'],['当前状态','Status','select']],items:[['设计系统 · 已验收','Design system · Approved'],['API 集成 · 审核中','API integration · In review'],['正式发布 · 待开始','Production launch · Planned']]}}
const key=document.body.dataset.project,p=projects[key];let lang=localStorage.getItem('demo-lang')||'zh';
const tr=x=>Array.isArray(x)?x[lang==='zh'?0:1]:x;
function render(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=tr(p.name)+' · Ruozhu Labs';document.querySelector('#app').innerHTML=`<div class="shell"><nav class="nav"><div class="brand">RUOZHU <i>LABS</i></div><div class="row"><a class="btn" href="../../index.html">${lang==='zh'?'返回作品集':'Back to profile'}</a><button class="btn" id="lang">${lang==='zh'?'EN':'中文'}</button></div></nav><section class="hero"><div><div class="eyebrow">LIVE PRODUCT DEMO · 产品演示</div><h1>${tr(p.name)}</h1><p class="muted">${tr(p.tag)}</p><button class="btn primary" onclick="document.querySelector('#demo').scrollIntoView({behavior:'smooth'})">${lang==='zh'?'打开工作区':'Open workspace'}</button></div><div class="card"><b>${lang==='zh'?'演示说明':'Demo note'}</b><p class="muted">${lang==='zh'?'这是可交互的前端演示。数据保存在当前浏览器，不会上传真实客户信息。':'This is an interactive frontend demo. Data stays in this browser and no real client information is uploaded.'}</p></div></section><section class="grid">${p.stats.map(s=>`<div class="card stat"><span class="muted">${tr(s)}</span><strong>${s[2]}</strong></div>`).join('')}</section><section class="workspace" id="demo"><form class="card" id="form"><h2>${lang==='zh'?'创建记录':'Create record'}</h2>${p.form.map((f,i)=>`<label class="field"><span>${tr(f)}</span>${f[2]==='textarea'?`<textarea name="f${i}" required></textarea>`:f[2]==='select'?`<select name="f${i}"><option>${lang==='zh'?'标准':'Standard'}</option><option>${lang==='zh'?'优先':'Priority'}</option></select>`:`<input name="f${i}" type="${f[2]}" required>`}</label>`).join('')}<button class="btn primary">${lang==='zh'?'保存并运行':'Save & run'}</button></form><div class="card"><div class="row" style="justify-content:space-between"><h2>${lang==='zh'?'实时活动':'Live activity'}</h2><span class="pill">${lang==='zh'?'已同步':'Synced'}</span></div><div class="list" id="list">${loadItems().map(x=>`<div class="item"><b>${tr(x)}</b><span class="muted">${lang==='zh'?'刚刚更新':'Updated just now'}</span></div>`).join('')}</div></div></section><footer class="footer">${lang==='zh'?'由陈若竹设计与开发 · 中英双语产品原型':'Designed and built by Ruozhu Chen · Bilingual product prototype'}</footer></div>`;document.querySelector('#lang').onclick=()=>{lang=lang==='zh'?'en':'zh';localStorage.setItem('demo-lang',lang);render()};document.querySelector('#form').onsubmit=e=>{e.preventDefault();const vals=[...new FormData(e.target).values()].filter(Boolean);const rows=JSON.parse(localStorage.getItem('demo-'+key)||'[]');rows.unshift([vals.join(' · '),vals.join(' · ')]);localStorage.setItem('demo-'+key,JSON.stringify(rows.slice(0,5)));render()}}
function loadItems(){return[...JSON.parse(localStorage.getItem('demo-'+key)||'[]'),...p.items].slice(0,6)}render();
